import type { LucideIcon } from "lucide-react"
import {
  Activity,
  Apple,
  Bone,
  Brain,
  Bug,
  Droplets,
  Eye,
  Flame,
  Heart,
  HeartPulse,
  Leaf,
  Mic,
  Pill,
  Shield,
  Smile,
  Sparkles,
  Syringe,
  ShieldAlert,
  Waves,
  Wind,
  Zap,
  GlassWater,
  AirVent,
} from "lucide-react"
import type { TherapyIconName } from "@/lib/types"

export const THERAPY_ICONS: Record<TherapyIconName, LucideIcon> = {
  pill: Pill,
  bone: Bone,
  bug: Bug,
  shield: Shield,
  virus: ShieldAlert,
  brain: Brain,
  activity: Activity,
  droplets: Droplets,
  smile: Smile,
  mic: Mic,
  syringe: Syringe,
  heart: Heart,
  flame: Flame,
  wind: Wind,
  "heart-pulse": HeartPulse,
  waves: Waves,
  sparkles: Sparkles,
  "glass-water": GlassWater,
  eye: Eye,
  zap: Zap,
  apple: Apple,
  "air-vent": AirVent,
  leaf: Leaf,
}
